name: noa
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  logging: ^1.2.0
  image: ^4.1.7
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  sign_in_with_apple: ^6.1.0
  url_launcher: ^6.2.6
  archive: ^3.5.0
  webview_flutter: ^4.7.0
  saver_gallery: ^3.0.5
  uuid: ^4.4.0
  collection: ^1.18.0
  just_audio: ^0.9.37
  path_provider: ^2.1.3
  audio_session: ^0.1.19
  flutter_foreground_task: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  ios: true
  android: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/2x/
    - assets/images/tutorial/
    - assets/lua_scripts/